name: Publish to NPM using pnpm

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - 'packages/storyshot/**'

jobs:
  build-and-publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js with pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org/"
          cache: "pnpm"

      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate

      - name: Install Dependencies
        run: cd packages/storyshot && pnpm install

      - name: Build Project
        run: cd packages/storyshot && pnpm run build

      - name: Publish to NPM
        run: cd packages/storyshot && pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}